default_platform(:ios)

before_all do
  git_pull # Pull the latest code
end

platform :ios do
  desc "Increment build number and version"
  lane :update_version do
    # Get the current plist version
    plist_version = get_version_number_from_plist(xcodeproj: './ios/AppCheck.xcodeproj')
    UI.message "Bumping patch version"
    increment_version_number_in_plist(xcodeproj: './ios/AppCheck.xcodeproj', bump_type: 'patch')
  end

  desc "Build the .ipa only"
  lane :build_ipa do
    # Increment the build number
    increment_build_number(xcodeproj: './ios/AppCheck.xcodeproj')

    # Build the .ipa using Gym
    gym(
      workspace: './ios/AppCheck.xcworkspace', # Path to your Xcode workspace
      scheme: 'AppCheck', # Your app's scheme
      export_method: 'app-store', # Method for app distribution (app-store, ad-hoc, enterprise)
      output_directory: './build', # Output directory for the .ipa
      output_name: 'AppCheck.ipa' # Name of the generated .ipa file
    )
  end
end
