default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :build_and_upload_to_testflight do
    # No need to use `match`, using local provisioning profiles and certificates instead

    # Build the app using Gym
    gym(
      workspace: "./ios/AppCheck.xcworkspace",
      scheme: "AppCheck",
      export_method: "app-store",
      output_directory: "./build",
      output_name: "AppCheck.ipa",
      timeout: 6000 # 6000 seconds = 1 hour 40 minutes
    )

    # Upload the build to TestFlight
    upload_to_testflight(
      username: ENV['ninehtz@gmail.com'], # Your Apple ID username for App Store Connect
      app_identifier: ENV['HR7RS84V6F.com.appchekongit']        # Your app bundle ID
    )
  end
end
