name: Build Android and iOS

on:
  push:
    branches:
      - master

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21.x'

    - name: Install dependencies
      run: |
        npm install
        npm install -g react-native-cli
        cd ios
        pod install

    - name: Set up Ruby and Install Fastlane
      run: |
        gem install bundler
        bundle install

    - name: Authenticate with App Store Connect API
      env:
        APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
        APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
      run: |
        fastlane run app_store_connect_api_key
        bundle exec fastlane update_version
        bundle exec fastlane build_ipa

    - name: Commit version changes
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Automated version bump"
      continue-on-error: true

    - name: Upload IPA to artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ios-app
        path: build/AppCheck.ipa
